### ISSUE TITLE
What the hell is Authtoken? 

### ISSUE THREAD

**Issue by brotherbest** [techchipnet/CamPhish#101]
Actually I wanted to know that what is authtoken, it's asking for an authtoken to use it😅😅I don't know what's that, it will be nice if someone tells me. 
![Screenshot_2021-12-29-14-52-43-288_com termux](https://user-images.githubusercontent.com/96809906/147646884-5329558f-26fb-4277-b1b8-65cdc1d0c2d9.jpg)

**Comment by blblblblblblblblblblblblbl** [comment]
lmao ngrok authotoken can be found on ngrok website u just need to create an acc and verify ur mail adress

**Comment by imraj569** [comment]
*go to ngrok.com create a account using anything u like then just copy my highleted area as shown in screenshot and past in authoken thats it 

<img width="719" alt="ngrok" src="https://user-images.githubusercontent.com/53007802/147853498-b0017374-5bbc-49d2-918b-908d2b66d0d0.png">

*for some privacy issue i hide my authoken 
*before you start using this tool make sure you turn on your hotsport

**Comment by aminzikryy** [comment]
> *go to ngrok.com create a account using anything u like then just copy my highleted area as shown in screenshot and past in authoken thats it
> 
> <img alt="ngrok" width="719" src="https://user-images.githubusercontent.com/53007802/147853498-b0017374-5bbc-49d2-918b-908d2b66d0d0.png">
> 
> *for some privacy issue i hide my authoken *before you start using this tool make sure you turn on your hotsport

./ngrok http ????

**Comment by brotherbest** [comment]
> lmao ngrok authtoken can be found on ngrok website u just need to create an acc and verify ur mail adress

Thanks bro👌

**Comment by brotherbest** [comment]
Thank you guys, but now I know, I have already made an account and copied my authtoken, but still you tried to help me, thanks
