### ISSUE TITLE
Error 105

### ISSUE THREAD

**Issue by mehedyhassanratul** [techchipnet/CamPhish#169]
`camphish.sh: line 105: which: command not found
camphish.sh: line 105: -c: command not found`

**Comment by Hiten8828** [comment]
Update 105 error

**Comment by ajtazer** [comment]
**Same Issue**
<img width="682" alt="image" src="https://github.com/techchipnet/CamPhish/assets/37796611/bfa3e86e-9b07-4af5-90d0-2f4d0391f760">
