### ISSUE TITLE
Camphish share related issue 

### ISSUE THREAD

**Issue by mdadil89** [techchipnet/CamPhish#175]
bro jab mai isko open karke share kar rha hu to sirf victim ke pass kch text ja rha hai mai chahta hu ki jitne bhi logo ke pass ye link jaye or jitne log isko open kare un sare ke img capture ho jaye or main baat ye hai ki share karne par iska link khud se nhi aa rha hai sirf kch word hindi mai likha hua hai bas isko resolve karo bhai

**Comment by techchipnet** [comment]
check the updated version of the camphish.
