### ISSUE TITLE
Ngrok

### ISSUE THREAD

**Issue by hamad12125** [techchipnet/CamPhish#177]
[+] Do you want to change your ngrok authtoken? [Y/n]: y
[+] Enter your valid ngrok authtoken: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[*] Authtoken has been changed
[+] Starting php server...
[+] Starting ngrok server...
[!] Direct link is not generating, check following possible reason
ngrok

**Comment by 183up** [comment]
https://github.com/techchipnet/CamPhish.git

**Comment by techchipnet** [comment]
check the updated version of the camphish.
