### ISSUE TITLE
I can't see cam image. What should I do? It's not visible in the file. 

### ISSUE THREAD

**Issue by AMIT-4505M** [techchipnet/CamPhish#179]

**Comment by Cursedblademaster** [comment]
The cam - taken pictures are saved in the camphish folder directly... If u can't see the images / pictures then it would ask in your browser then allow it Deny option for the camera to open...


Recheck on those things

**Comment by antor1010101010** [comment]
It's not my device,  when send the link other device allow but the image is
full black

**Comment by techchipnet** [comment]
check the updated version of the camphish.

**Comment by spbhaisare358** [comment]
I'm using the updated version but not working properly only see the black image like this I'm attech the image check

![Image](https://github.com/user-attachments/assets/2f3fffc4-4734-4960-a728-e882f5c0bfe5)
