### ISSUE TITLE
pic aren't not visible

### ISSUE THREAD

**Issue by antor1010** [techchipnet/CamPhish#184]
when i send the link and open this using mobile i don't see the cam file this is full black please slove the problem
![cam05Dec2023183210](https://github.com/techchipnet/CamPhish/assets/151869057/74503061-1315-4f97-a4d6-759120c1da51)

**Comment by Mohd-arham3848** [comment]
Bro how to open cam file ?

**Comment by Mohd-arham3848** [comment]
@ @antor1010 .

**Comment by techchipnet** [comment]
check the updated version of the camphish.
