### ISSUE TITLE
Link not generating

### ISSUE THREAD

**Issue by Niyaz5** [techchipnet/CamPhish#191]
I can't get the link it's says link is not generating and give possible reason why not generating but i've tried that's all reason is correct in my case then also is link not generating please reply
![Screenshot_20240323_134716_Termux](https://github.com/techchipnet/CamPhish/assets/144505585/48e503f8-5377-493f-935d-8090a868bbd5)

**Comment by Bababoy43** [comment]
ok thanks


Ghost ***@***.***> escreveu (sábado, 23/03/2024 à(s) 08:21):

**Comment by techchipnet** [comment]
Check the updated version of the camphish. termux & ngrok issues fixed
