### ISSUE TITLE
Direct link is not generating, check following possible reason

### ISSUE THREAD

**Issue by mohammadakram2007** [techchipnet/CamPhish#194]
I am using termux 
I will follow correct instructions by it come 

!
![Screenshot_20240419_092736_Termux](https://github.com/techchipnet/CamPhish/assets/167225122/a8f69084-84bd-412f-9709-ea3cccc44ed1)

If you know please tell how to solve

**Comment by techchipnet** [comment]
issue has been fixed now please check the updated version.

**Comment by hacksanju** [comment]
Again issue hai link not guaranting

**Comment by Negoohdewalker** [comment]
> 1. Try by creating a new ngrok account.
> 2. make sure your hostpot is on.
> 3. Try "kill " or ctrl+C

Null

**Comment by v9363151-hub** [comment]
[!] Direct link is not generating, check following possible reason

**Comment by v9363151-hub** [comment]
[!] Direct link is not generating, check following possible reason

**Comment by v9363151-hub** [comment]
[!] Direct link is not generating, check following possible reason

**Comment by abderahmenamry-ai** [comment]
i got the same problem here how can i fix it
