### ISSUE TITLE
hi sir, there is a issue occuring. Link is not generating in linux and termux

### ISSUE THREAD

**Issue by DemonRocky** [techchipnet/CamPhish#3]
![Screenshot from 2020-04-13 20-18-01](https://user-images.githubusercontent.com/63089072/79130281-561ca000-7dc4-11ea-82f7-a25670476083.png)

**Comment by Pawan83** [comment]
@DemonRocky Just restart the phone enable the internet connection and hotspot. It will definitely works.

**Comment by Dbagwani** [comment]
sir 
will it not work on wifi in termux

**Comment by Dbagwani** [comment]
![Screenshot_2020-04-14-05-36-52-1311977011](https://user-images.githubusercontent.com/63621159/79172325-0369d500-7e12-11ea-9ce9-687650c8e1a5.png)
sir I'm facing this problem in termux

**Comment by DemonRocky** [comment]
> @DemonRocky Just restart the phone enable the internet connection and hotspot. It will definitely works.

i just changed the port number then it worked fine.....

**Comment by Dbagwani** [comment]
How did you change it?
