### ISSUE TITLE
Link is no displayed. 

### ISSUE THREAD

**Issue by Jay582** [techchipnet/CamPhish#6]
Please help... 

![Screenshot_2020-04-14-13-05-32-281_com termux](https://user-images.githubusercontent.com/63636000/79198730-94ac6c00-7e51-11ea-9649-ed0012a662f3.jpg)

**Comment by Jay582** [comment]
The issue got solved but can you please let me know how to view the cam files?

**Comment by akrho1973** [comment]
Plz pass link tnx

**Comment by anonixoo7** [comment]
thanks

**Comment by ashley2605** [comment]
> The issue got solved but can you please let me know how to view the cam files?

xdg-open (camfile name)
